---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python:
          mass_threshold: 40
      - php
  pep8:
    enabled: true
    checks:
      E731:
        enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 2
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
